# Copyright 2023-2024 The MathWorks, Inc.
# Build, Test & Publish matlab-deps/r2023a/ubi9
name: matlab-deps-r2023a-ubi9

# Define when builds will occur:
on:
  # Run workflow when there is a push to the 'main' branch & push includes changes to any files in described path
  push:
    branches:
      - 'main'
    paths:
      - 'matlab-deps/r2023a/ubi9/**'
      - '/tests/matlab-deps/**'
      - 'tests/pytools/**'

  # Run at 00:00 on every Monday (1st Day of the Week) (See: crontab.guru)
  schedule:
    - cron: '0 0 * * 1'

  workflow_dispatch:

jobs:
  build-test-and-publish-image:
    uses: ./.github/workflows/build-test-and-publish-dependencies-image.yml
    secrets: inherit
    with:
        docker_build_context: './matlab-deps/r2023a/ubi9'
        base_image_name: mathworks/matlab-deps
        matlab_release_tag: 'r2023a'
        os_info_tag: 'ubi9'
        is_default_os: false
        should_add_latest_tag: false
        test_file_path: 'tests/matlab-deps/test_ubi9.py'
