# Copyright 2023 The MathWorks, Inc.
# Build & Publish polyspace-deps/r2023a/ubuntu20.04
name: polyspace-deps-r2023a-ubuntu20.04

# Define when builds will occur:
on:
  # Run workflow when there is a push to the 'main' branch & push includes changes to any files in described path
  push:
    branches:
      - 'main'
    paths:
      - 'polyspace-deps/r2023a/ubuntu20.04/**'

  # Run at 00:00 on every Monday (1st Day of the Week) (See: crontab.guru)
  schedule:
    - cron: '0 0 * * 1'

  workflow_dispatch:

jobs:
  build-and-publish-docker-image:
    uses: ./.github/workflows/build-and-publish-docker-image.yml
    secrets: inherit
    with:
        docker_build_context: './polyspace-deps/r2023a/ubuntu20.04'
        base_image_name: mathworks/polyspace-deps
        matlab_release_tag: 'r2023a'
        os_info_tag: 'ubuntu20.04'
        is_default_os: true
        should_add_latest_tag: false